# Generated by Django 4.1.7 on 2023-03-09 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='updatd_at',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='updatd_at',
            new_name='updated_at',
        ),
    ]
