# Generated by Django 4.1.7 on 2023-03-10 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0003_transaction_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_number',
            field=models.CharField(editable=False, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='account_number',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='bank.account'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.FloatField(editable=False),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_id',
            field=models.CharField(editable=False, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('deposit', 'deposit'), ('withdrawal', 'withdrawal')], editable=False, max_length=50),
        ),
    ]
