# Generated by Django 4.1.7 on 2023-03-10 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0006_alter_account_account_number_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='account_number',
            new_name='account_number_id',
        ),
    ]
